version: '3.5'
services:
  # loadbalancer:
  #   image: traefik
  #   # command: --docker --docker.watch
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 8080:8080 # Træfik dashboard
  #   volumes:
  #     # Required so Traefik can see new or changed deployments.
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     # Mounted so we can Hot-reload config
  #     - ./traefik.toml:/etc/traefik/traefik.toml
    # labels:
    #   - traefik.frontend.rule=Host:traefik.recipe.localhost
    #   - "traefik.enable=true"
    #   - "traefik.port=8080"
    #   - traefik.backend.loadbalancer.method=wrr
    # deploy:
    #   restart_policy:
    #     condition: any
    #   mode: replicated
    #   replicas: 1
    #   update_config:
    #     delay: 2s
    #   placement:
    #     constraints: 
    #       - node.role == manager
    #       - node.labels.name != db
    #   labels:
    #     - traefik.frontend.rule=Host:traefik.recipe.localhost
    #     - "traefik.enable=true"
    #     - "traefik.port=8080"
    #     - "traefik.frontend.entryPoints=http"
    # networks:
    #   - traefik-net
    # depends_on:
    #   - recipe-api
    #   - recipe-web
    # secrets:
    #     - bladehq.com.crt
    #     - bladehq.com.key
    #     - bladeplay.com.crt
    #     - bladeplay.com.key
    #     - flytaniumco.com.crt
    #     - flytaniumco.com.key
    #     - arcformknives.com.crt
    #     - arcformknives.com.key
        # TODO: add other stores
  recipe-api:
    image: jlwarren1/recipe-api
    build: 
      context: ./api
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    labels:
      - traefik.backend=recipe-api
      # - traefik.docker.network=traefik-net
      # - traefik.docker.network=recipe_mysql
      # - traefik.docker.network=bridge
      - traefik.enable=true
      - traefik.frontend.rule=Host:api.recipe.localhost
      - "traefik.docker.network=traefik_webgateway"
      # - traefik.frontend.priority=1
      # - traefik.port=80
      # - "traefik.frontend.entryPoints=http"
      # - traefik.backend.loadbalancer.method=wrr
      # - "traefik.backend.loadbalancer.stickiness=true"
      # - "traefik.backend.loadbalancer.stickiness.cookieName=_blaze"
    volumes:
      - ./templates:/templates
      - ./static:/static
    expose:
      - "80"
    # ports:
    #   - 8999:8999
    environment:
      PORT: 80
      DB_HOST: mysql:3306
      DB_PASS_FILE: /run/secrets/mysql_password
      DB_USER_FILE: /run/secrets/mysql_user
      DB_NAME_FILE: /run/secrets/mysql_name
    networks:
      - mysql
      - web
    depends_on:
      - mysql
    secrets:
      - mysql_root_password
      - mysql_name
      - mysql_user
      - mysql_password
  recipe-web:
    image: jlwarren1/recipe-web
    build: 
      context: ./web
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    labels:
      - traefik.backend=recipe-web
      # - traefik.docker.network=traefik-net
      # - traefik.docker.network=recipe_mysql
      # - traefik.docker.network=bridge
      - traefik.enable=true
      - traefik.frontend.rule=Host:recipe.localhost,www.recipe.localhost
      - "traefik.docker.network=traefik_webgateway"
      # - traefik.frontend.priority=1
      # - traefik.port=80
      # - "traefik.frontend.entryPoints=http"
      # - "traefik.backend.loadbalancer.stickiness=true"
      # - "traefik.backend.loadbalancer.stickiness.cookieName=_blaze"
    volumes:
      - ./templates:/templates
      - ./static:/static
    expose:
      - "80"
    # ports:
    #   - 8999:8999
    environment:
      PORT: 80
      DB_HOST: mysql:3306
      DB_PASS_FILE: /run/secrets/mysql_password
      DB_USER_FILE: /run/secrets/mysql_user
      DB_NAME_FILE: /run/secrets/mysql_name
    networks:
      - mysql
      - web
    depends_on:
      - mysql
    secrets:
      - mysql_root_password
      - mysql_name
      - mysql_user
      - mysql_password
  mysql:
    image: mariadb:10.3
    restart: always
    labels:
      - traefik.enable=false
    ports:
      - '3306:3306'
    networks:
      - mysql
    volumes:
      - ./.docker/database/_data:/var/lib/mysql
      - ./.docker/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_name
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_name
      - mysql_user
      - mysql_password
secrets:
  mysql_root_password:
    file: ./.docker/database/secrets/mysql_root_password.txt
  mysql_name:
    file: ./.docker/database/secrets/mysql_name.txt
  mysql_user:
    file: ./.docker/database/secrets/mysql_user.txt
  mysql_password:
    file: ./.docker/database/secrets/mysql_password.txt
networks:
  mysql:
    driver: bridge
  web:
    external:
      name: traefik_webgateway
