version: '2'
# https://github.com/go-task/task
tasks:
  up:
    deps:
     - task: lb-up
     - task: web-up
  lb-up:
    dir: ./traefik
    cmds:
      - docker-compose up -d
  web-up:
    cmds:
      - docker-compose up -d
  web-down:
    cmds:
      - docker-compose down
  web-restart:
    deps:
      - task: web-down
      - task: web-up
  build-all:
    deps:
     - task: build-api
     - task: build-web
  build-api: 
    dir: ./api
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -a -tags netgo -o recipe-api -ldflags '-w' .
      - docker-compose build recipe-api
  build-web: 
    dir: ./web
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -a -tags netgo -o recipe-web -ldflags '-w' .
      - docker-compose build recipe-web
  gen-all:
    deps:
     - task: generate-all
  generate-all:
    deps:
     - task: generate-api
     - task: generate-web
  generate-api:
    dir: ./api
    cmds:
      - goagen bootstrap -d github.com/jaredwarren/recipe/api/design
      - goagen app -d github.com/jaredwarren/recipe/api/design
  gen-web:
    deps:
     - task: generate-web
  generate-web:
    dir: ./web
    cmds:
      - goagen bootstrap -d github.com/jaredwarren/recipe/web/design
      - goagen app -d github.com/jaredwarren/recipe/web/design