accessLogsFile = "/dev/stdout"
logLevel = "DEBUG"
# defaultEntryPoints = ["http", "https"]
defaultEntryPoints = ["http"]
debug = false

# For testing
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
domain = "recipe.com"
# swarmmode = false
exposedbydefault = false

# API definition
[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true