basePath: /recipe
consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateRecipePayload:
    properties:
      value:
        description: Operand value
        format: int64
        type: integer
    required:
    - value
    title: CreateRecipePayload
    type: object
  RecipeCategory:
    description: A Category (default view)
    properties:
      categories:
        $ref: '#/definitions/RecipeCategoryCollection'
      name:
        example: Commodi autem aut.
        type: string
      type:
        example: Voluptatum architecto et non.
        type: string
    required:
    - name
    title: 'Mediatype identifier: application/recipe.category+json'
    type: object
  RecipeCategoryCollection:
    description: RecipeCategoryCollection is the media type for an array of RecipeCategory
      (default view)
    example:
    - categories:
      - categories: '-'
        name: Commodi autem aut.
        type: Voluptatum architecto et non.
      - categories: '-'
        name: Commodi autem aut.
        type: Voluptatum architecto et non.
      name: Commodi autem aut.
      type: Voluptatum architecto et non.
    items:
      $ref: '#/definitions/RecipeCategory'
    title: 'Mediatype identifier: application/recipe.category+json; type=collection'
    type: array
  RecipeCookware:
    description: A Cookware (default view)
    properties:
      description:
        description: long description
        example: Voluptas quo libero vel numquam sint consequuntur.
        type: string
      name:
        description: what's it called
        example: Quis esse provident.
        type: string
      parts:
        $ref: '#/definitions/RecipeCookwareCollection'
      settings:
        description: settings, e.g. temprature
        example:
        - Enim voluptatem.
        - Enim voluptatem.
        - Enim voluptatem.
        items:
          example: Enim voluptatem.
          type: string
        type: array
      setup:
        $ref: '#/definitions/RecipeStepCollection'
    required:
    - name
    title: 'Mediatype identifier: application/recipe.cookware+json'
    type: object
  RecipeCookwareCollection:
    description: RecipeCookwareCollection is the media type for an array of RecipeCookware
      (default view)
    example:
    - description: Voluptas quo libero vel numquam sint consequuntur.
      name: Quis esse provident.
      parts:
      - description: Voluptas quo libero vel numquam sint consequuntur.
        name: Quis esse provident.
        parts: '-'
        settings:
        - Enim voluptatem.
        - Enim voluptatem.
        - Enim voluptatem.
        setup:
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
      - description: Voluptas quo libero vel numquam sint consequuntur.
        name: Quis esse provident.
        parts: '-'
        settings:
        - Enim voluptatem.
        - Enim voluptatem.
        - Enim voluptatem.
        setup:
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
      - description: Voluptas quo libero vel numquam sint consequuntur.
        name: Quis esse provident.
        parts: '-'
        settings:
        - Enim voluptatem.
        - Enim voluptatem.
        - Enim voluptatem.
        setup:
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
      settings:
      - Enim voluptatem.
      - Enim voluptatem.
      - Enim voluptatem.
      setup:
      - description: Minus nobis debitis corporis odit quo odit.
        title: Dolor unde natus iusto.
      - description: Minus nobis debitis corporis odit quo odit.
        title: Dolor unde natus iusto.
    - description: Voluptas quo libero vel numquam sint consequuntur.
      name: Quis esse provident.
      parts:
      - description: Voluptas quo libero vel numquam sint consequuntur.
        name: Quis esse provident.
        parts: '-'
        settings:
        - Enim voluptatem.
        - Enim voluptatem.
        - Enim voluptatem.
        setup:
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
      - description: Voluptas quo libero vel numquam sint consequuntur.
        name: Quis esse provident.
        parts: '-'
        settings:
        - Enim voluptatem.
        - Enim voluptatem.
        - Enim voluptatem.
        setup:
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
      - description: Voluptas quo libero vel numquam sint consequuntur.
        name: Quis esse provident.
        parts: '-'
        settings:
        - Enim voluptatem.
        - Enim voluptatem.
        - Enim voluptatem.
        setup:
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
        - description: Minus nobis debitis corporis odit quo odit.
          title: Dolor unde natus iusto.
      settings:
      - Enim voluptatem.
      - Enim voluptatem.
      - Enim voluptatem.
      setup:
      - description: Minus nobis debitis corporis odit quo odit.
        title: Dolor unde natus iusto.
      - description: Minus nobis debitis corporis odit quo odit.
        title: Dolor unde natus iusto.
    items:
      $ref: '#/definitions/RecipeCookware'
    title: 'Mediatype identifier: application/recipe.cookware+json; type=collection'
    type: array
  RecipeNote:
    description: A Note (default view)
    properties:
      id:
        description: Unique ID
        example: 2.0978439e+18
        format: int64
        type: integer
      text:
        description: html text
        example: Dolorem laudantium soluta saepe.
        type: string
    required:
    - id
    - text
    title: 'Mediatype identifier: application/recipe.note+json'
    type: object
  RecipeNoteCollection:
    description: RecipeNoteCollection is the media type for an array of RecipeNote
      (default view)
    items:
      $ref: '#/definitions/RecipeNote'
    title: 'Mediatype identifier: application/recipe.note+json; type=collection'
    type: array
  RecipeRecipe:
    description: A recipe (default view)
    properties:
      categories:
        $ref: '#/definitions/RecipeCategoryCollection'
      cook_time:
        description: Amount of time to cook
        example: 1987-01-20T08:51:16-07:00
        format: date-time
        type: string
      cookware:
        $ref: '#/definitions/RecipeCookwareCollection'
      created:
        description: First created
        example: 1991-08-27T18:42:04-06:00
        format: date-time
        type: string
      description:
        description: Long description of recipe
        example: Rerum ex est voluptas at.
        type: string
      difficulty:
        description: rating between 0-1
        example: 0.707592
        maximum: 1
        type: number
      directions:
        $ref: '#/definitions/RecipeStepCollection'
      favorite:
        description: Is a favorite, basically a tag
        example: true
        type: boolean
      id:
        description: Unique recipe ID
        example: 6.4767986e+18
        format: int64
        type: integer
      images:
        description: Title of recipe
        example:
        - Autem voluptatem.
        items:
          example: Autem voluptatem.
          type: string
        type: array
      ingredients:
        $ref: '#/definitions/RecipeRecipeCollection'
      notes:
        $ref: '#/definitions/RecipeNoteCollection'
      prep_time:
        description: Amount of time to prepare
        example: 2015-04-16T08:11:47-06:00
        format: date-time
        type: string
      quantity:
        $ref: '#/definitions/RecipeUnitofmeasure'
      rating:
        description: rating between 0-1
        example: 0.25973496
        maximum: 1
        type: number
      source:
        $ref: '#/definitions/RecipeSource'
      tags:
        $ref: '#/definitions/RecipeTagCollection'
      title:
        description: Title of recipe
        example: Quo aut quia voluptas.
        type: string
      updated:
        description: Last Updated
        example: 1988-10-08T08:19:55-06:00
        format: date-time
        type: string
      version:
        description: Version Number e.g. 1.0.1
        example: Dolorem voluptatem esse explicabo est.
        type: string
      wait_time:
        description: Amount of time to wait for things such as mairnading
        example: 2012-02-24T05:39:21-07:00
        format: date-time
        type: string
    required:
    - id
    - title
    title: 'Mediatype identifier: application/recipe.recipe+json'
    type: object
  RecipeRecipeCollection:
    description: RecipeRecipeCollection is the media type for an array of RecipeRecipe
      (default view)
    items:
      $ref: '#/definitions/RecipeRecipe'
    title: 'Mediatype identifier: application/recipe.recipe+json; type=collection'
    type: array
  RecipeSource:
    description: A Source (default view)
    properties:
      id:
        description: Unique ID
        example: 3.3200938e+18
        format: int64
        type: integer
      name:
        example: Sequi sit saepe in eligendi repellendus aut.
        type: string
      url:
        example: In rerum doloribus nihil omnis voluptas eum.
        type: string
    required:
    - id
    - name
    title: 'Mediatype identifier: application/recipe.source+json'
    type: object
  RecipeStep:
    description: A Step (default view)
    properties:
      description:
        description: HTML
        example: Minus nobis debitis corporis odit quo odit.
        type: string
      title:
        example: Dolor unde natus iusto.
        type: string
    required:
    - title
    title: 'Mediatype identifier: application/recipe.step+json'
    type: object
  RecipeStepCollection:
    description: RecipeStepCollection is the media type for an array of RecipeStep
      (default view)
    items:
      $ref: '#/definitions/RecipeStep'
    title: 'Mediatype identifier: application/recipe.step+json; type=collection'
    type: array
  RecipeTag:
    description: A Tag (default view)
    properties:
      name:
        example: Asperiores alias rerum molestias esse nisi.
        type: string
    required:
    - name
    title: 'Mediatype identifier: application/recipe.tag+json'
    type: object
  RecipeTagCollection:
    description: RecipeTagCollection is the media type for an array of RecipeTag (default
      view)
    items:
      $ref: '#/definitions/RecipeTag'
    title: 'Mediatype identifier: application/recipe.tag+json; type=collection'
    type: array
  RecipeUnitofmeasure:
    description: A recipe (default view)
    properties:
      name:
        description: name e.g. Cups, Table Spoon
        example: Aperiam deserunt maiores voluptatum.
        type: string
      type:
        default: weight
        description: volume, weight, time, length...
        example: Adipisci voluptatum tenetur.
        type: string
    required:
    - name
    title: 'Mediatype identifier: application/recipe.unitofmeasure+json'
    type: object
  UpdateRecipePayload:
    properties:
      value:
        description: Operand value
        format: int64
        type: integer
    required:
    - value
    title: UpdateRecipePayload
    type: object
externalDocs:
  description: TODO
  url: http://jlwarren1.com/recipe/docs
host: localhost:8080
info:
  contact:
    email: jlwarren1@gmail.com
    name: Jared Warren
    url: http://jlwarren1.com
  description: CRUD API recipe
  license:
    name: MIT
    url: https://github.com/goadesign/goa/blob/master/LICENSE
  title: Recipe App
  version: ""
paths:
  /recipe:
    post:
      operationId: recipe#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateRecipePayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/RecipeRecipe'
      schemes:
      - http
      summary: create recipe
      tags:
      - recipe
  /recipe/{id}:
    delete:
      operationId: recipe#delete
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/RecipeRecipe'
      schemes:
      - http
      summary: delete recipe
      tags:
      - recipe
    get:
      description: Display an recipe by id
      operationId: recipe#show
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/RecipeRecipe'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show recipe
      tags:
      - recipe
    put:
      operationId: recipe#update
      parameters:
      - in: path
        name: id
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateRecipePayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/RecipeRecipe'
      schemes:
      - http
      summary: update recipe
      tags:
      - recipe
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/RecipeRecipe'
schemes:
- http
swagger: "2.0"
